version: '2'
services:
  explorer:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    image: explorer
    container_name: ark-explorer 
    restart: always
    working_dir: /var/www/explorer
    volumes:
      - explorer:/var/www/explorer
    tty: true
    network_mode: host
volumes:
  explorer:
    driver_opts:
      type: none
      device: $PWD/../
      o: bind
      